

DOCKER_DUT_DEBUG=1
LCOW_MODE=1
SKIPCOPY_GO=1
SKIP_ALL_CLEANUP=yes
SKIP_BINARY_BUILD=1
SKIP_COPY_GO=1
SKIP_IMAGE_BUILD=1
SKIP_VALIDATION_TESTS=1
SOURCES_DRIVE=c
SOURCES_SUBDIR=gopath
TESTRUN_DRIVE=c
TESTRUN_SUBDIR=CI
